spring.application.name=fresh-keep

server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.ai.google.genai.api-key=${SPRING_AI_GOOGLE_GENAI_API_KEY}
spring.datasource.driver-class-name=org.postgresql.Driver

# 'update' creates the table if it does not exist. For real production environment, set to 'validate'.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

logging.level.org.springframework=INFO
logging.level.root=INFO

